export const ANIMATIONS = [
  'Acknowledge',
  'Alert',
  'Announce',
  'Blink',
  'Confused',
  'Congratulate',
  'Congratulate_2',
  'Decline',
  'DoMagic1',
  'DoMagic2',
  'DontRecognize',
  'Explain',
  'GestureDown',
  'GestureLeft',
  'GestureRight',
  'GestureUp',
  'GetAttention',
  'GetAttentionContinued',
  'GetAttentionReturn',
  'Greet',
  'Hearing_1',
  'Hearing_2',
  'Hearing_3',
  'Hearing_4',
  'Hide',
  'Idle1_1',
  'Idle1_2',
  'Idle1_3',
  'Idle1_4',
  'Idle2_1',
  'Idle2_2',
  'Idle3_1',
  'Idle3_2',
  'LookDown',
  'LookDownBlink',
  'LookDownReturn',
  'LookLeft',
  'LookLeftBlink',
  'LookLeftReturn',
  'LookRight',
  'LookRightBlink',
  'LookRightReturn',
  'LookUp',
  'LookUpBlink',
  'LookUpReturn',
  'MoveDown',
  'MoveLeft',
  'MoveRight',
  'MoveUp',
  'Pleased',
  'Process',
  'Processing',
  'Read',
  'ReadContinued',
  'ReadReturn',
  'Reading',
  'RestPose',
  'Sad',
  'Search',
  'Searching',
  'Show',
  'StartListening',
  'StopListening',
  'Suggest',
  'Surprised',
  'Think',
  'Thinking',
  'Uncertain',
  'Wave',
  'Write',
  'WriteContinued',
  'WriteReturn',
  'Writing',
] as const;

export type AnimationName = (typeof ANIMATIONS)[number];

const ANIMATION_SET: ReadonlySet<string> = new Set(ANIMATIONS);
export function isAnimationName(value: string): value is AnimationName {
  return ANIMATION_SET.has(value);
}

export const PREEMPTING_ANIMATIONS: ReadonlySet<AnimationName> = new Set([
  'Hide',
  'Show',
  'GetAttention',
] as const);

export const IDLE_ANIMATIONS: readonly AnimationName[] = [
  'Idle1_1',
  'Idle1_2',
  'Idle1_3',
  'Idle1_4',
  'Idle2_1',
  'Idle2_2',
  'Idle3_1',
  'Idle3_2',
  'Blink',
  'LookLeft',
  'LookRight',
];
